### PR TITLE
Support processed res deRedundancy

### PR DESCRIPTION
**Pull request by lwj1994**
解压 .ap_  -> 删除重复的文件，再重新定位 arsc 重复的资源 -> 重新打包 .ap_

### CODE REVIEW

**Comment by johnsonlee** [comment]
Could you show me an example of duplicated entries in `.ap_` archive file?

**Comment by lwj1994** [comment]
@johnsonlee I added the relevant log to report.

it will check  duplicated entries in same parent file.

## test 
### test demo

deme's layout, drawable has duplicated files:
* `ic_launcher_background.xml` duplicated with `ic_launcher_background2.xml`, ` ic_launcher_background3.xml`
* `activity_main2.xml`  duplicated with  `activity_main3.xml`,`activity_main5.xml`,`activity_main7.xml`

see its report:
```
0.85% intermediates/processed_res/debug/out/resources-debug.ap_ 8,167 961,453 /Users/luwenjie/Documents/demo/SlowFunctionCheckDemo/app/build/intermediates/processed_res/debug/out/resources-debug.ap_
---------------------------------------------------------------------
 TOTAL                                                          8,167

removed 1 entry duplicated with Entry:[name:res/color/checkbox_themeable_attribute_color.xml, crc:106581170, size:464]:
1. Entry:[name:res/color/radiobutton_themeable_attribute_color.xml, crc:106581170, size:464]

removed 1 entry duplicated with Entry:[name:res/color/mtrl_bottom_nav_colored_ripple_color.xml, crc:2638324326, size:948]:
1. Entry:[name:res/color/mtrl_tabs_colored_ripple_color.xml, crc:2638324326, size:948]

removed 1 entry duplicated with Entry:[name:res/color/mtrl_bottom_nav_ripple_color.xml, crc:153417060, size:1672]:
1. Entry:[name:res/color/mtrl_tabs_ripple_color.xml, crc:153417060, size:1672]

removed 1 entry duplicated with Entry:[name:res/color/mtrl_navigation_item_icon_tint.xml, crc:945490082, size:624]:
1. Entry:[name:res/color/mtrl_navigation_item_text_color.xml, crc:945490082, size:624]

removed 1 entry duplicated with Entry:[name:res/color-v23/abc_tint_edittext.xml, crc:1954525703, size:668]:
1. Entry:[name:res/color-v23/abc_tint_spinner.xml, crc:1954525703, size:668]

removed 2 entry duplicated with Entry:[name:res/drawable/ic_launcher_background.xml, crc:3985735082, size:5696]:
1. Entry:[name:res/drawable/ic_launcher_background2.xml, crc:3985735082, size:5696]
2. Entry:[name:res/drawable/ic_launcher_background3.xml, crc:3985735082, size:5696]

removed 1 entry duplicated with Entry:[name:res/drawable/mtrl_popupmenu_background.xml, crc:1492599386, size:740]:
1. Entry:[name:res/drawable/mtrl_popupmenu_background_dark.xml, crc:1492599386, size:740]

removed 1 entry duplicated with Entry:[name:res/interpolator/btn_checkbox_checked_mtrl_animation_interpolator_0.xml, crc:1170948913, size:316]:
1. Entry:[name:res/interpolator/btn_checkbox_unchecked_mtrl_animation_interpolator_0.xml, crc:1170948913, size:316]

removed 1 entry duplicated with Entry:[name:res/interpolator/btn_checkbox_checked_mtrl_animation_interpolator_1.xml, crc:3970749230, size:328]:
1. Entry:[name:res/interpolator/btn_checkbox_unchecked_mtrl_animation_interpolator_1.xml, crc:3970749230, size:328]

removed 1 entry duplicated with Entry:[name:res/interpolator/btn_radio_to_off_mtrl_animation_interpolator_0.xml, crc:2960756502, size:320]:
1. Entry:[name:res/interpolator/btn_radio_to_on_mtrl_animation_interpolator_0.xml, crc:2960756502, size:320]

removed 3 entry duplicated with Entry:[name:res/layout/activity_main2.xml, crc:245409587, size:880]:
1. Entry:[name:res/layout/activity_main3.xml, crc:245409587, size:880]
2. Entry:[name:res/layout/activity_main5.xml, crc:245409587, size:880]
3. Entry:[name:res/layout/activity_main7.xml, crc:245409587, size:880]

removed 1 entry duplicated with Entry:[name:res/mipmap-anydpi-v26/ic_launcher.xml, crc:1146363823, size:448]:
1. Entry:[name:res/mipmap-anydpi-v26/ic_launcher_round.xml, crc:1146363823, size:448]
```



### test on my app
report:
```
0.46% intermediates/processed_res/release/out/resources-release.ap_ 7,990 1,740,548 /Users/luwenjie/Documents/androidStudioProjects/mygithub/xbtc-android/app/build/intermediates/processed_res/release/out/resources-release.ap_
-------------------------------------------------------------------------
 TOTAL                                                              7,990

removed 1 entry duplicated with Entry:[name:res/anim/nav_default_enter_anim.xml, crc:2324485647, size:460]:
1. Entry:[name:res/anim/nav_default_pop_enter_anim.xml, crc:2324485647, size:460]

removed 1 entry duplicated with Entry:[name:res/anim/nav_default_exit_anim.xml, crc:1627603134, size:460]:
1. Entry:[name:res/anim/nav_default_pop_exit_anim.xml, crc:1627603134, size:460]

removed 1 entry duplicated with Entry:[name:res/animator/nav_default_enter_anim.xml, crc:2354174408, size:452]:
1. Entry:[name:res/animator/nav_default_pop_enter_anim.xml, crc:2354174408, size:452]

removed 1 entry duplicated with Entry:[name:res/animator/nav_default_exit_anim.xml, crc:2143089099, size:452]:
1. Entry:[name:res/animator/nav_default_pop_exit_anim.xml, crc:2143089099, size:452]

removed 1 entry duplicated with Entry:[name:res/color/checkbox_themeable_attribute_color.xml, crc:2371085192, size:464]:
1. Entry:[name:res/color/radiobutton_themeable_attribute_color.xml, crc:2371085192, size:464]

removed 1 entry duplicated with Entry:[name:res/color/mtrl_bottom_nav_colored_ripple_color.xml, crc:3344682506, size:948]:
1. Entry:[name:res/color/mtrl_tabs_colored_ripple_color.xml, crc:3344682506, size:948]

removed 1 entry duplicated with Entry:[name:res/color/mtrl_bottom_nav_ripple_color.xml, crc:542667710, size:1672]:
1. Entry:[name:res/color/mtrl_tabs_ripple_color.xml, crc:542667710, size:1672]

removed 1 entry duplicated with Entry:[name:res/color/mtrl_navigation_item_icon_tint.xml, crc:1622613214, size:624]:
1. Entry:[name:res/color/mtrl_navigation_item_text_color.xml, crc:1622613214, size:624]

removed 1 entry duplicated with Entry:[name:res/color-v23/abc_tint_edittext.xml, crc:4249494616, size:668]:
1. Entry:[name:res/color-v23/abc_tint_spinner.xml, crc:4249494616, size:668]

removed 2 entry duplicated with Entry:[name:res/drawable/abc_ratingbar_indicator_material.xml, crc:1548506544, size:124]:
1. Entry:[name:res/drawable/abc_ratingbar_material.xml, crc:1548506544, size:124]
2. Entry:[name:res/drawable/abc_ratingbar_small_material.xml, crc:1548506544, size:124]

removed 1 entry duplicated with Entry:[name:res/drawable/ic_darkmode_24dp.xml, crc:1677281061, size:2028]:
1. Entry:[name:res/drawable/ic_setting_darkmode.xml, crc:1677281061, size:2028]

removed 1 entry duplicated with Entry:[name:res/drawable/mtrl_popupmenu_background.xml, crc:861533045, size:740]:
1. Entry:[name:res/drawable/mtrl_popupmenu_background_dark.xml, crc:861533045, size:740]

removed 1 entry duplicated with Entry:[name:res/interpolator/btn_checkbox_checked_mtrl_animation_interpolator_0.xml, crc:1013122958, size:316]:
1. Entry:[name:res/interpolator/btn_checkbox_unchecked_mtrl_animation_interpolator_0.xml, crc:1013122958, size:316]

removed 1 entry duplicated with Entry:[name:res/interpolator/btn_checkbox_checked_mtrl_animation_interpolator_1.xml, crc:2500106129, size:328]:
1. Entry:[name:res/interpolator/btn_checkbox_unchecked_mtrl_animation_interpolator_1.xml, crc:2500106129, size:328]

removed 1 entry duplicated with Entry:[name:res/interpolator/btn_radio_to_off_mtrl_animation_interpolator_0.xml, crc:3385969577, size:320]:
1. Entry:[name:res/interpolator/btn_radio_to_on_mtrl_animation_interpolator_0.xml, crc:3385969577, size:320]

removed 2 entry duplicated with Entry:[name:res/layout/page_preupload_config.xml, crc:2745024722, size:360]:
1. Entry:[name:res/layout/view_prime.xml, crc:2745024722, size:360]
2. Entry:[name:res/layout/view_pwd_login.xml, crc:2745024722, size:360]

removed 1 entry duplicated with Entry:[name:res/mipmap-anydpi-v26/ic_launcher.xml, crc:800106227, size:448]:
1. Entry:[name:res/mipmap-anydpi-v26/ic_launcher_round.xml, crc:800106227, size:448]
```

**Comment by johnsonlee** [comment]
I quite confused, what's the definition of the term `duplicated entry`?

**Comment by lwj1994** [comment]
isn't same crc😂?

**Comment by johnsonlee** [comment]
What if some resources with same CRC have been used by code?

**Comment by lwj1994** [comment]
the value which entry is duplicated  in arsc  has relocation to first resource. Is there a problem with who exit first？
maybe you mean getting resources not through R.X.X. intead of accessing  file directly in some other way？delete this files will cause exception.

**Comment by johnsonlee** [comment]
Not the case, if no duplicate entries exist, it's a waste of I/O twice

**Comment by lwj1994** [comment]
thank you , i will check it

**Pull request closed without merging**
